### ISSUE TITLE
README lacks installation instructions.

### ISSUE THREAD

**Issue by PanderMusubi** [achromaticmetaphor/agram#2]
Please, add a button "Get it on F-Droid" with a PNG file from https://commons.wikimedia.org/wiki/File:Get_it_on_F-Droid.svg in your README file with the appropriate link to the page of your app on F-Droid.

**Comment by PanderMusubi** [comment]
Would you add it if I offer a pull request?

**Comment by achromaticmetaphor** [comment]
@PanderMusubi A pull request would not be sufficient. I am open to further discussion on the matter, but I don't immediately understand why I would recommend binaries from a third party to someone who has already found the source repository. Perhaps the README should include instructions for installing from source, with F-Droid presented as an alternative.
